Add Pi for F0 != 0 (T < Tc). Remove (k=0, omega=0) from Omega fit.
Point removed from omega fit since A*B terms in new Pi are singular there.
Removing this from the fit did not change the result of tempCrit test. It
had small effects on the tempFluc tests:

--- FAIL: TestEnergies (0.26 seconds)
    energy_test.go:30: unexpected pair energy value 0.008298245972734044
                                          (expected 0.008298245919880036)
--- FAIL: TestSolveFlucSystem (9.85 seconds)
    system_test.go:40: unexpected solution; got
         [0.0164111381183055 -0.5778732662210768 2.750651172711139] and
expected [0.01641113805141947 -0.5778732666052968 2.750651176253013]
--- FAIL: TestSolveFlucSystem_LargeMu_b (14.73 seconds)
    system_test.go:63: unexpected solution; got
         [0.03047703936397049 -0.7236663299469903 1.7649274240769777] and
expected [0.030477040639422425 -0.7236663239242993 1.7649273942043424]

After fixing the TestSolveFlucSystem expected output (which TestEnergies
depends on), got:

--- FAIL: TestEnergies (0.00 seconds)
    energy_test.go:23: unexpected holon energy value 0.011309275258310362
                                           (expected 0.011309275210763277)

--- FAIL: TestEnergies (0.25 seconds)
    energy_test.go:30: unexpected pair energy value 0.00829824598441264
                                          (expected 0.008298245972734044)